all:main

main: question1.cpp question2.cpp question3.cpp question4.cpp question5.cpp
	g++ -o question1 question1.cpp
	g++ -o question2 question2.cpp
	g++ -o question3 question3.cpp
	g++ -o question4 question4.cpp
	g++ -o question5 question5.cpp

question1: question1.cpp
	g++ -o question1 question1.cpp
question2: question2.cpp
	g++ -o question2 question2.cpp
question3: question3.cpp
	g++ -o question3 question3.cpp
question4: question4.cpp
	g++ -o question4 question4.cpp
question5: question5.cpp
	g++ -o question5 question5.cpp
clean:
	rm -f question1 question2 question3 question4 question5